[project]
name = "unforgettable"
version = "0.2.0"
license = "MIT"
description = "Unforgettable is a simple cache you can used for tiny repetitive executions."
authors = [
    { name = "Cesar Cardoso", email = "hello@cesarcardoso.cc" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
unforgettable = "unforgettable.cli:main"

[dependency-groups]
dev = [
    "coverage>=7.14.1",
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.bumpversion]
tag = true
tag_name = "v{new_version}"
pre_commit_hooks = ["printf \"# CHANGELOG\n\n\" > CHANGELOG.md && git log v0.1.1..HEAD --format=\"* %h %s\" >> CHANGELOG.md", "git add CHANGELOG.md", "uvx isort ./src", "uvx black ./src", "git add src", "uv sync --upgrade", "git add uv.lock"]
commit = true

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[[tool.bumpversion.files]]
filename = "README.md"

[[tool.bumpversion.files]]
filename = "Makefile"
